import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://atsuat.bbsi.com/login');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('chaitanya.chintalapudi@bbsihq.com');
  await page.locator('vaadin-button').click();
  await page.getByRole('textbox', { name: 'Enter your email, phone, or' }).click();
  await page.getByRole('textbox', { name: 'Enter your email, phone, or' }).fill('chaitanya.chintalapudi@bbsihq.com');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Enter the password for' }).click();
  await page.getByRole('textbox', { name: 'Enter the password for' }).fill('Ss831Cc#2521~');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'No' }).click();
  // await page.goto('https://atsuat.bbsi.com/dashboard');
  await page.waitForURL('https://atsuat.bbsi.com/dashboard', {timeout: 60000});
  await page.locator('span').nth(1).click();
  await page.getByRole('link', { name: 'Top Menu Icon Applicant List' }).click();
  await page.getByRole('button', { name: 'Bright, Ella' }).click();
  await page.getByRole('tab', { name: 'Interviews' }).click();
  await page.getByRole('button', { name: 'Schedule Interview' }).click();
  await page.getByRole('combobox').selectOption('93');
  await page.getByRole('textbox', { name: 'MM/DD/YYYY' }).click();
  await page.getByText('28').click();
  await page.locator('#start-timepicker').getByRole('textbox', { name: 'hours' }).click();
  await page.locator('#start-timepicker').getByRole('textbox', { name: 'hours' }).fill('10');
  await page.getByRole('row', { name: '10  :      AM' }).getByPlaceholder('MM').click();
  await page.getByRole('row', { name: '10  :      AM' }).getByPlaceholder('MM').fill('00');
  await page.getByRole('row', { name: ':      AM' }).getByPlaceholder('HH').click();
  await page.getByRole('row', { name: ':      AM' }).getByPlaceholder('HH').fill('11');
  await page.getByRole('row', { name: ':      AM' }).getByPlaceholder('MM').click();
  await page.getByRole('row', { name: ':      AM' }).getByPlaceholder('MM').fill('00');
  await page.locator('span').filter({ hasText: 'Select' }).first().click();
  await page.getByText('Belmont Cameli (belmontcameli').click();
  await page.locator('div').filter({ hasText: 'Type of Interview *' }).nth(2).click();
  await page.getByRole('checkbox', { name: 'Send Email to Applicant' }).check();
  await page.getByRole('button', { name: 'Schedule' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: '×' }).click();
  await page.waitForTimeout(3000);
});